### ISSUE TITLE
【WIP】新增v2版本操作例子

### ISSUE THREAD

**Issue by silenceper** [gowechat/example#2]

**Comment by silenceper** [comment]
https://github.com/silenceper/wechat/issues/161

**Comment by silenceper** [comment]
https://github.com/silenceper/wechat/issues/179

**Comment by xzeu** [comment]
.\main.go:29:27: cannot use func literal (type func("github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) *"github.com/silenceper/wechat/v2/officialaccount/message".Reply) as type func(*"github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) *"github.com/silenceper/wechat/v2/officialaccount/message".Reply in argument to server.SetMessageHandler

**Comment by Mrli2016** [comment]
> .\main.go:29:27: cannot use func literal (type func("github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) _"github.com/silenceper/wechat/v2/officialaccount/message".Reply) as type func(_"github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) *"github.com/silenceper/wechat/v2/officialaccount/message".Reply in argument to server.SetMessageHandler

我也遇到同样的问题

**Comment by silenceper** [comment]
@Mrli2016  @xzeu  解决了，主要是sdk更新了，这里类型没有更新。 重新更新一下master分支代码：


8bba1c7f05e8738fdfd7fde1bffe29be060a19a3
