### ISSUE TITLE
当发送消息是没反应

### ISSUE THREAD

**Issue by reasoll** [gowechat/example#9]
![image](https://user-images.githubusercontent.com/22016109/155545187-ca95db9f-24a0-4477-a306-4541fa34a602.png)
![1c6985eac6731ba12cc45686a07fd2e](https://user-images.githubusercontent.com/22016109/155545469-0c8a4321-a900-4d87-8260-78795a9a5f7d.jpg)
发送消息时后台可以看到，但是聊天界面显示服务故障，请问是什么情况

**Comment by itachilee** [comment]
同问

**Comment by silenceper** [comment]
服务端没有正确返回，看下log信息

**Comment by liujianying** [comment]
都一样，没正确回复，微信直接判断异常了

**Comment by xcxxcx1996** [comment]
服务端的Serve 回复函数写错啦，类型改成文本类型就好了
[https://github.com/gowechat/example/blob/master/pkg/officialAccount/officialAccount.go#L47](url)
